/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIExample */

#ifndef _Included_JNIExample
#define _Included_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIExample
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_accessframework_WindowsXpContext_getApplication
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_accessframework_WindowsXpContext_getSystemKey
  (JNIEnv *, jclass, jstring, jstring, jstring);

JNIEXPORT jstring JNICALL Java_accessframework_WindowsXpContext_getUserKey
  (JNIEnv *, jclass, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_accessframework_WindowsXpContext_setSystemKey
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_accessframework_WindowsXpContext_setUserKey
    (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_accessframework_WindowsXpContext_refreshRegistry
  (JNIEnv *env, jclass obj, jint x, jint y, jint val);

JNIEXPORT void JNICALL Java_accessframework_WindowsXpContext_refreshRegistryAlt
  (JNIEnv *env, jclass obj, jint x, jint y, jint val);

JNIEXPORT void JNICALL Java_accessframework_WindowsXpContext_refreshFilterKeys
  (JNIEnv *env, jclass obj, jint code, jint iwait, jint idelay, jint irepeat, jint ibounce);

JNIEXPORT void JNICALL Java_accessframework_WindowsXpContext_refreshMouse
  (JNIEnv *env, jclass obj, jint speed, jint thresh1, jint thresh2);

JNIEXPORT jint JNICALL Java_accessframework_WindowsXpContext_queryMouseThreshold1
  (JNIEnv *env, jclass obj);

JNIEXPORT jint JNICALL Java_accessframework_WindowsXpContext_queryMouseThreshold2
  (JNIEnv *env, jclass obj);

JNIEXPORT jint JNICALL Java_accessframework_WindowsXpContext_queryMouseAcceleration
  (JNIEnv *env, jclass obj);
#ifdef __cplusplus
}
#endif
#endif
